# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: "Code Review"
description: "Do code reviews based on input"
author: "juhlinus"

branding:
  # https://actions-cool.github.io/github-action-branding/
  icon: "file"
  color: "blue"

inputs:
  token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
  json_output:
    description: The JSON output from ECS
    required: true

runs:
  using: "node12"
  main: "dist/index.js"
